name: "Publish scripts"

on:
  push:
    branches:
      - master
    paths:
      - scripts/**

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Publish scripts to Cloudflare Pages
    steps:
      - name: Check out
        uses: actions/checkout@v4

